# Задание 1.15

Найти собственный ортонормированный базис и матрицу в этом базисе самосопряжённого оператора $\varphi$, заданного матрицей
$$A_{\varphi}^{(e)}=\begin{pmatrix}17&-8&4\\-8&17&-4\\4&-4&11\end{pmatrix}.$$


## Теория

Матрица симметрична → самосопряжённый оператор.  
Находим собственные значения и собственные векторы, ортогонализуем и нормируем.  
Матрица в новом базисе — диагональная с собственными значениями на диагонали.


In [2]:
import numpy as np

A = np.array([[17,-8,4],[-8,17,-4],[4,-4,11]], dtype=float)
vals, vecs = np.linalg.eigh(A)  # для симметричных матриц

print("Собственные значения:", vals)

# Ортонормированный базис (столбцы vecs уже ортонормированы)
Q = vecs
print("Ортонормированный базис (столбцы):\n", Q)
print("Проверка Q^T Q = I:\n", Q.T @ Q)
print("Матрица в новом базисе (диагональная):\n", Q.T @ A @ Q)


Собственные значения: [ 9.  9. 27.]
Ортонормированный базис (столбцы):
 [[ 0.68338391 -0.29756004 -0.66666667]
 [ 0.72524316  0.17198231  0.66666667]
 [ 0.08371849  0.93908472 -0.33333333]]
Проверка Q^T Q = I:
 [[ 1.00000000e+00  3.29337809e-17 -1.52284425e-16]
 [ 3.29337809e-17  1.00000000e+00 -1.62493987e-17]
 [-1.52284425e-16 -1.62493987e-17  1.00000000e+00]]
Матрица в новом базисе (диагональная):
 [[9.00000000e+00 9.04944060e-17 3.67285956e-15]
 [5.97003909e-16 9.00000000e+00 4.27370641e-16]
 [2.80331314e-15 1.55431223e-15 2.70000000e+01]]
