# Задание 1.16

Найти ортогональное преобразование, приводящее квадратичную функцию к главным осям:
$$f(x_1,x_2,x_3,x_4)=3x_1^2+8x_1x_2-3x_2^2+4x_3^2-4x_3x_4+x_4^2.$$


## Теория

Квадратичная форма распадается на две независимые:  
$f_1 = 3x_1^2+8x_1x_2-3x_2^2$ и $f_2 = 4x_3^2-4x_3x_4+x_4^2$.  
Составляем симметричные матрицы, находим собственные значения и векторы.  
Ортогональное преобразование — матрица из собственных векторов.


In [2]:
import numpy as np

# Блок 1: 3x1^2 + 8x1x2 - 3x2^2  -> матрица [[3,4],[4,-3]]
A1 = np.array([[3,4],[4,-3]], dtype=float)
w1, V1 = np.linalg.eigh(A1)

# Блок 2: 4x3^2 - 4x3x4 + x4^2 -> матрица [[4,-2],[-2,1]]
A2 = np.array([[4,-2],[-2,1]], dtype=float)
w2, V2 = np.linalg.eigh(A2)

print("Блок 1: собственные значения", w1)
print("Блок 1: собственные векторы\n", V1)
print("Блок 2: собственные значения", w2)
print("Блок 2: собственные векторы\n", V2)

# Общее ортогональное преобразование — блочно-диагональное
Q = np.zeros((4,4))
Q[:2,:2] = V1
Q[2:,2:] = V2
print("Ортогональная матрица Q:\n", Q)

# Канонический вид
print("Канонический вид: ", w1[0], "*y1^2 +", w1[1], "*y2^2 +", w2[0], "*y3^2 +", w2[1], "*y4^2")


Блок 1: собственные значения [-5.  5.]
Блок 1: собственные векторы
 [[ 0.4472136  -0.89442719]
 [-0.89442719 -0.4472136 ]]
Блок 2: собственные значения [0. 5.]
Блок 2: собственные векторы
 [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
Ортогональная матрица Q:
 [[ 0.4472136  -0.89442719  0.          0.        ]
 [-0.89442719 -0.4472136   0.          0.        ]
 [ 0.          0.         -0.4472136  -0.89442719]
 [ 0.          0.         -0.89442719  0.4472136 ]]
Канонический вид:  -5.0 *y1^2 + 5.0 *y2^2 + 0.0 *y3^2 + 5.0 *y4^2
